# Generated by Django 4.2.5 on 2023-09-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(max_length=200)),
                ('address_number', models.IntegerField()),
                ('localidad', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.address')),
            ],
        ),
        migrations.CreateModel(
            name='RehearsalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.location')),
                ('rehearsal_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.rehearsaltype')),
            ],
        ),
        migrations.CreateModel(
            name='ChoirSinger',
            fields=[
                ('id_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.address')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.rehearsal')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.choirsinger')),
            ],
        ),
    ]
