# Generated by Django 4.2.5 on 2023-09-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(max_length=200)),
                ('address_number', models.IntegerField()),
                ('localidad', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='choirsinger',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='attendance.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.address'),
        ),
    ]
